### ISSUE TITLE
No reply from golive email

### ISSUE THREAD

**Issue by mikey0000** [electrickiwi-nz/api-samples#10]
Hi could I have confirmation that my email to golive has been recieved? Would be good to know its been a few weeks now.

**Comment by electrickiwi-nz** [comment]
@mikey0000 - really sorry that you have not heard back from us earlier. 

I have just sent you an email regarding your app to go-live. If you can read that and respond, we can help in getting you live credentials. 

Cheers, Matt

**Comment by mikey0000** [comment]
Nothing in my inbox can you send to my email address listed on github perhaps? Maybe your mail provider isn't sending it to me?

27/01/2023 8:06:13 pm Electric Kiwi | Juice Hackers ***@***.***>:

**Comment by electrickiwi-nz** [comment]
@mikey0000 - I have tried again using your github listed email. Hopefully that works. 🤞

**Comment by mikey0000** [comment]
Yeah that works, I should remove Hotmail from github... Though you've sent me an email about the wrong repo/a different Mike.

**Comment by mikey0000** [comment]
So there is this repo
https://github.com/mikey0000/Python-ElectricKiwiApi

And the home assistant integration in the core repo under the electric kiwi api branch, instructions should be in my email. My email was sent from Arthur.kiwi.nz domain

**Comment by mikey0000** [comment]
@electrickiwi-nz Matt did you manage to find my email to golive?

**Comment by mikey0000** [comment]
Hi Matt
Would really appreciate a reply.

More than happy to help get the integration running on a call etc

thanks

**Comment by electrickiwi-nz** [comment]
@mikey0000 - thanks for your patients on this ... I have managed to understand what has gone on and what you have been working on. 

Firstly, nice work creating the Electric Kiwi integration into Home Assistant and creating the Pull Request for them to integrate. 

I note that they have not provided guidance on the client_id and client_secret integration or handling and we have been discussing internally if this should be a single id and key for the integration or specific to the user who will be using the integration. We are leaning toward a specific one to the user but are waiting to see what the home assistant team say as to how to apply these which may adjust our thinking. 

As for the integration, it looks like it uses the Python API you built - nice work - and uses some of the same patterns Flick's integration has. 

As next steps - are you ok to keep working with Home Assistant team to get guidance on how client_id and client_secrets are handled? Once we know this we can look at how we should share id and key and with who. 

Cheers, Matt

**Comment by mikey0000** [comment]
As per their documentation them being issued a client_id and secret is the recommended way.

https://developers.home-assistant.io/docs/core/platform/application_credentials

Cloud Account Linking with Cloud Component: Nabu Casa registers credentials with the cloud provider, providing a seamless user experience. This approach provides a seamless user experience and is recommended

The built-in OAuth2 support works out of the box with locally configured client ID / secret using the [Application Credentials platform](https://developers.home-assistant.io/docs/core/platform/application_credentials) and with the Home Assistant Cloud Account Linking service. This service allows users to link their account with a centrally managed client ID/secret. If you want your integration to be part of this service, reach out to us at [hello@home-assistant.io](mailto:hello@home-assistant.io).

If you don't mind issuing me a production set, even if its temporary, It should hopefully help me proceed with getting the integration merged and working on further features and discussion with them.

The API actually follows Home Assistants pattern for APIs and yes Flick also follow the same, the HA integration was inspired by Flicks but of course is still different.

I purposely avoided the whole, hand over your username and password some integrations do to get a token, so there needs to be some sane balance here otherwise someone will do it if the process is too painful.

**Comment by mikey0000** [comment]
please do get in touch via email or other means as it would be good to have a proper meeting/talk than this back and forth.

So first up is to email hello@home-assistant.io I doubt they are going to bother with me since I'm not working for Electric Kiwi
