### ISSUE TITLE
Production Oauth server down/not responding

### ISSUE THREAD

**Issue by mikey0000** [electrickiwi-nz/api-samples#11]
welcome.electrickiwi.co.nz is not responding/timing out so users cannot authenticate.

**Comment by electrickiwi-nz** [comment]
@mikey0000 - sorry about that ... I am just following up with the team to see if there is something specific that has happened. I will get back to you shortly.

**Comment by electrickiwi-nz** [comment]
@mikey0000 - as part of maintenance last night new security policies were introduced on the OAuth server. We have since made further updates and confirmed access is now working again. 

Thanks for letting us know.
