### ISSUE TITLE
Refresh token issues HA

### ISSUE THREAD

**Issue by mikey0000** [electrickiwi-nz/api-samples#12]
Sorry I'm not sure what the best way to go about this, emails seem to get lost sometimes so I'll raise this here.

When in production HA(Nabu Casa cloud) is returning 500 errors when trying to refresh the token, it's my understanding that the nabucasa cloud (in this instance) is acting much like a proxy, are there any issues visible at your end? At least so I can debug the problem if at all. 

I'll test the dev environment later on and see if it does it. 

This is in production and its affected/ING everyone whos using my home assistant integration.

**Comment by electrickiwi-nz** [comment]
@mikey0000 - thanks for posting the issue - I have the team looking into what may have changed and will get back to you once I have an update. Sorry.

**Comment by mikey0000** [comment]
Hey I went looking through old emails and found one about the refresh token expiring, any chance you've changed the expiry time on that?

**Comment by mikey0000** [comment]
anyway I've reduced the time between api calls and it seems to have resolved the issue. Looks to be an expiry problem. Need to sift through emails and check how long the refresh token lasts for.

**Comment by electrickiwi-nz** [comment]
@mikey0000 - sorry for the inconvenience caused - we have fixed the refresh token issue and will look to extend the expiry to be 5 days which will help with the performance of the HA app meaning that users don't need to login as often.
