### ISSUE TITLE
API Access

### ISSUE THREAD

**Issue by damianpeterson** [electrickiwi-nz/api-samples#14]
Hi and sorry for using issues to communicate here but I've not had any response after contacting support through the website chat. 
I registered for API access a couple of weeks ago and have heard nothing since. Not sure if there's supposed to be any kind of email confirmation after registration but haven't received anything like that. 

Is this API access still a thing?

Can anyone point me to someone I can contact about it?

Thanks in advance.

**Comment by electrickiwi-nz** [comment]
@damianpeterson - sorry for the late response. The API is still working and we processed the registration on the 7th July. Can you please check your spam folder of your email address you used to signup for Electric Kiwi for a response from info@electrickiwi.co.nz to your registration? 

The email has your client id and secret and some information about what to do and how to develop an app using our API. 

If you don't find the email there - can you message us and we will resend the email. 

Cheers, Matt

**Comment by damianpeterson** [comment]
Strange. I don't have anything from EK from that time period. Spam or otherwise. It's possible I entered my email address incorrectly. Can you try resending it?

**Comment by electrickiwi-nz** [comment]
@damianpeterson - I will resend the registration in the next 5 minutes ...

**Comment by electrickiwi-nz** [comment]
@damianpeterson - just sent it ... let me know if it is received else I will look to alternate ways to get you the details.

**Comment by damianpeterson** [comment]
Perfect. Got it. Thanks!
