### ISSUE TITLE
Incorrect inactive hour of power

### ISSUE THREAD

**Issue by damianpeterson** [electrickiwi-nz/api-samples#15]
Hi. Just noticed that in dev via the API and in production by using the web interface hour number 48 (which is between 2330 and 0030) is marked as inactive:
```json
 "48": {
  "active": 0,
  "end_time": "12:30 AM",
  "start_time": "11:30 PM"
}
```
I think this is incorrect given the public-facing website states, "The off-peak time slots are between 9am-5pm and 9pm-7am every day."

**Comment by electrickiwi-nz** [comment]
Hi Damian,

Thank you for your question. In regards to the granular range for the Hour of Power, we consider a day as the required timeframe. Within this range, the Hour of Power should consist of two consecutive half-hour intervals. As Interval 48 is not continuous within a single day, it has not been activated.

I hope this clarifies your question.

Thanks,
Umesh

**Comment by damianpeterson** [comment]
Ok thanks. Makes sense.
