### ISSUE TITLE
Home Assistant 2023.8 release with EK integration

### ISSUE THREAD

**Issue by mikey0000** [electrickiwi-nz/api-samples#16]
Sent an email a few days ago with no reply, but the integration I've been working on has been merged and is going out in the next release of Home Assistant.

Thanks for the collab in making it happen and I'll continue to add additional features over time.

https://www.home-assistant.io/blog/2023/08/02/release-20238/#new-integrations

**Comment by mikey0000** [comment]
2023.9 will contain the select entity for selecting HOP and has been merged.

**Comment by electrickiwi-nz** [comment]
@mikey0000 - congratulations and nice work on getting the Electric Kiwi Integration into Home Assistant. It is a great piece of work and we look forward to seeing more functionality coming through in the plugin.

Cheers, Matt
