### ISSUE TITLE
Refresh tokens expiring too quickly

### ISSUE THREAD

**Issue by damianpeterson** [electrickiwi-nz/api-samples#19]
Hey it looks like refresh tokens have reverted to expiring too quickly again. The last few months have been perfect but the last couple of days they've gone back to only a few hours.

**Comment by electrickiwi-nz** [comment]
@damianpeterson - sorry about that ... I am checking with the team if anything has changed over the weekend that has inadvertently disrupted your settings. I should hear back sometime today and I will let you know. 

Cheers, Matt

**Comment by electrickiwi-nz** [comment]
@damianpeterson - I have not gotten to the bottom of what happened but the team have adjusted your token to have the same timeout as previous and you should see your app working correctly again. Sorry for the inconvenience caused.

**Comment by damianpeterson** [comment]
Thanks Matt
