### ISSUE TITLE
Does the /consumption/summary/ endpoint return real time data?

### ISSUE THREAD

**Issue by dixoncheng** [electrickiwi-nz/api-samples#3]
Hi there, just wondering if the /consumption/summary/ endpoint return real time data or how much of a delay is there? 

In other words can I get data for the current day or can I only get data for the previous day after passing midnight?

Thanks!

**Comment by electrickiwi-nz** [comment]
Hey Dixon - great question. The electricity consumption data comes from the metering providers (not Electric Kiwi) and it's a delayed service. The consumption data is made available via the API endpoints, /consumption/summary/ and /consumption/averages/ as soon as we receive it. Generally, reads arrive between 48-72 hours behind real-time as a rule of thumb. 

I hope this helps. Cheers.

**Comment by dixoncheng** [comment]
Thanks, ah this won't work for me then. I'm thinking to build a function that runs just before midnight and checks the current day's consumption and set the HOP to the hour with most consumption.

**Comment by electrickiwi-nz** [comment]
There are alternative third party hardware solutions to obtain real time consumption data which you can still achieve the same outcome. Sounds like a great project - let us know how you go!

I will look to process your API request shortly so you have access to the sandbox environment to play with our API. 

Cheers, Matt
