### ISSUE TITLE
Account Sign In

### ISSUE THREAD

**Issue by Muchengeti** [electrickiwi-nz/api-samples#4]
What account is used to authenticate? An existing Electric Kiwi account or can you create a new account solely for use of the sandbox

**Comment by electrickiwi-nz** [comment]
Hi, if you read over the API Documentation here: https://developer.electrickiwi.co.nz/api-documentation/ we have a sandbox environment that you can use while developing. There are a number of test accounts (50) which can be used for authentication within this sandbox environment. Check out the `Sandbox Environment` and `Sandbox Accounts` sections.

Once your development is complete and you are happy with how it is working, send us a link to your GitHub repository that contains your live widget source code so we can fork and review. Once we've confirmed there are no nasties we'll issue you with live access keys. These live access keys will allow you, and customers, to login using live account credentials. 

Hope this helps. 

Cheers, Matt
