### ISSUE TITLE
Unable to signin using the local api sample

### ISSUE THREAD

**Issue by shaneprice** [electrickiwi-nz/api-samples#5]
Hi there,

I have signed up and have a sandbox account. I am now trying to get the sample python application working.

Running locally on my machine the sample web application starts up ok and im redirected to the https://welcome-dev.electrickiwi.co.nz/ page when I try use one of the 50 accounts as per the documentation they dont work. I have tried a number of email addresses e.g. api_dev+1@ekay.co.nz,api_dev+2@ekay.co.nz,api_dev+50@ekay.co.nz but none seem to work.

When registering for an account I was asked for a callback URL, I provided a domain I have access to but I dont have a current running website, I tried to supply localhost as the call back but the form considered that as invalid.

I have modified the REDIRECT_URI = f"http://{HOST}:{PORT}/callback" to be the website I used during registration but I get this error.

{ error: "invalid_request", error_description: "Invalid "redirect_uri" in request.", state: "super-secret-state" }

Is my issue related to the callback URL? Is there a developer portal where I can log into and change these kind of settings?

Can you please provide help to what I am doing wrong.

Thanks

**Comment by electrickiwi-nz** [comment]
Shane, 

Great that you have downloaded the python sample and looking to access the API. 

Currently, we don't have a developer portal for you to log into and make adjustments - so reaching out here is the best way. 

From looking at your registration and configuration there was a misconfiguration whereby the redirect_uri (callback) was missing our sample `http://localhost:5080/callback` URL. If you test the sample with the REDIRECT_URI set to the default (`http://localhost:5080/callback`) it should give you access via a local development environment. 

For your registered callback URL - this will work when you are hosting the python script on the https://penfy.com domain and you would need a separate callback path that will capture the OAuth2 token for use in other API calls. 

I have added `https://penfy.com/callback` to the redirect_uri's in case you want that as your callback. Happy to change it to whatever you need. 

Hope this helps... let me know if you need other assistance.

**Comment by shaneprice** [comment]
Thanks for coming back to me so quickly, adding localhost from your side helped me sign in and get a bearer token. I now see a mistake I made during signup and I didn't ask for all the scopes I needed. Could you please modify my account to have access to all available scopes.

Once development is complete I can then remove the scopes I don't actually end up using.

**Comment by electrickiwi-nz** [comment]
Shane, no worries on about the scopes - I have added all scopes for your testing. They include:

- read_customer_detail
- read_connection_detail
- read_billing_address
- read_billing_frequency
- read_billing_bills
- read_billing_bill
- read_billing_bill_file
- read_account_running_balance
- read_consumption_summary
- read_consumption_averages
- read_hop_intervals_config
- read_hop_connection
- save_hop_connection
- read_outage_contact
- read_session

Let me know if there is anything else. We look forward to seeing how you integrate Electric Kiwi into your [core](https://github.com/shaneprice/core) home automation system. 

Cheers, Matt
