### ISSUE TITLE
refresh token flow documentation is incorrect/not working

### ISSUE THREAD

**Issue by mikey0000** [electrickiwi-nz/api-samples#6]
Hi there,

The authorize endpoint is returning 500 on dev, next person who might actually get an integration into home assistant for electric kiwi haha, seems there have been a few half attempts.

**Comment by electrickiwi-nz** [comment]
@mikey0000 - thanks for the note. So sorry that you were getting a 500 error on the Authorize endpoint - we happened to be doing some upgrades to the backend while you were trying to use it. This is now fixed and I have tested with your sandbox Client ID and Client Secret and it is working as expected again. 

Yes there have be quite a few API requests for people using home assistant and we are keen as for a developer to get one working, maybe you will be the first?

Cheers, Matt

**Comment by mikey0000** [comment]
Thanks, Just working on a simple Python API to Electric Kiwi as per Home Assistants requirements, hopefully Electric Kiwi could take at least that over? Otherwise I guess I'll manage both the API and Integration. Yeah I am actively working on it so I should have the basic Python API done soon and the starting integration maybe in a week or so.

**Comment by mikey0000** [comment]
Actually its still down @electrickiwi-nz

**Comment by mikey0000** [comment]
FYI https://github.com/mikey0000/Python-ElectricKiwiApi Just need the authorize endpoint working so I can actually test it properly but please take a look, its published on pypi as well electrickiwi-api

**Comment by electrickiwi-nz** [comment]
@mikey0000 - I have just tested again and all parts of our OAuth2 authorization_token flow are working as expected. My sense is that the library you have created is not using the authorization_token flow to get a valid token to access our API. 

My suggestion is to look over our [Python API sample code](https://github.com/electrickiwi-nz/api-samples/tree/master/python) to see how a authorization_token flow works with the callback URL to get a token. We only support authorization_token and implicit token versions. Also your callback URL is either:
https://electrickiwi.coding.kiwi.nz/electrickiwi/callback
http://localhost:5080

Your library looks good - good luck.

**Comment by mikey0000** [comment]
cool will take a look starting at the sample.

**Comment by mikey0000** [comment]
Hi back again, can you tell me whats wrong with my refresh token request, I've followed the guide to the letter. Also your missing an extra / in https:/ in the docs

**Comment by mikey0000** [comment]
Hi I added the auth header and now I get {"status": 1, "error": {"code": 2, "title": "Client not recognised", "detail": "Invalid client access"}} which is probably the refresh process failing this time.

**Comment by electrickiwi-nz** [comment]
@mikey0000 - sorry for the late response ... I have been chatting with the team and they have not seen any errors with the refresh token but are looking into it. Can you confirm that you can use the initial bearer token as expected or is that giving issues too? We are looking to see what the issue maybe. Sorry for the trouble, refresh should be working but obviously is not. I will get back to you when we find the issue and implement a fix.

**Comment by mikey0000** [comment]
So I use the sample python application to get the token object then I've used postman to make the post request to renew the token using the example in the docs along with my own credentials and of course the refresh token. 

Purely to test it out and make sure it works as expected before getting to the home assistant integration. Happy to get on a call and sort it out. I'm a customer :D 

My API should be fairly stable now I rewrote it a bit to follow HA guide and so its more extensible/reusable, I'll be moving to implementation in home assistant now. 0.6.0 is published to pypi
https://github.com/mikey0000/Python-ElectricKiwiApi

**Comment by mikey0000** [comment]
If I don't include the auth header I get error "invalid_grant" grant_type is "refresh_token"

**Comment by mikey0000** [comment]
> @mikey0000 - sorry for the late response ... I have been chatting with the team and they have not seen any errors with the refresh token but are looking into it. Can you confirm that you can use the initial bearer token as expected or is that giving issues too? We are looking to see what the issue maybe. Sorry for the trouble, refresh should be working but obviously is not. I will get back to you when we find the issue and implement a fix.

Getting the initial bearer token works fine, just refreshing it doesn't seem to work.

**Comment by mikey0000** [comment]
Figured it out. Your documentation is wrong or there is something wrong with your implementation (bug). It also wasn't obvious that you need the basic auth for any request to the token endpoint, would be good to update the documentation with that.
To get a refresh token you need to post a form request e.g

```
import requests

url = "https://welcome-dev.electrickiwi.co.nz/oauth/token?grant_type=refresh_token"

payload={'refresh_token': 'some_token'}
files=[

]
headers = {
  'Authorization': 'Basic ABC'
}

response = requests.request("POST", url, headers=headers, data=payload, files=files)

print(response.text)
```

or

`curl --location --request POST 'https://welcome-dev.electrickiwi.co.nz/oauth/token?grant_type=refresh_token' \
--header 'Authorization: Basic ABC' \
--form 'refresh_token="some_token"'`

**Comment by electrickiwi-nz** [comment]
@mikey0000 - sorry for the slow response ... thanks for the heads up and you are right we have implemented the OAuth2 refresh_token a little incorrectly as how can you request a new token if your Bearer has expired. 

We were looking at the same thing yesterday and the team are looking to prioritise a fix but currently don't know when that may happen. 

I will look to update you when we have a clearer picture - sorry again for it being wrong.

**Comment by mikey0000** [comment]
No worries!

1/11/2022 12:57:24 pm Electric Kiwi | Juice Hackers ***@***.***>:

**Comment by mikey0000** [comment]
Just an FYI I was using Basic header not Bearer so refreshing after expiry will still work in its current form, will need to adjust my home assistant integration though.

**Comment by electrickiwi-nz** [comment]
@mikey0000 - this has taken a while to get to the bottom of... basically there were some changes implemented after the documentation was created but the documentation was not updated and you are the first to catch it since the changes. 

The documentation should say:

```
POST https://welcome.electrickiwi.co.nz/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic [client_id:client_secret]
Body
  grant_type=refresh_token
  refresh_token=def50200b971da5b299768af2534186244...
```

Using curl it should be:

```
curl --request POST \
  --url https://welcome-dev.electrickiwi.co.nz/oauth/token \
  --header 'Authorization: Basic [client_id:client_secret]' \
  --header 'Content-Type: multipart/form-data' \
  --form grant_type=refresh_token \
  --form refresh_token=def50200b971da5b299768af2534186244...
```

We will be updating the documentation shortly and appreciate you reaching out regarding it not working correctly.

I hope this clarifies everything - looking forward to seeing the Home Assistant implementation.

**Comment by mikey0000** [comment]
Brilliant, thanks.

3/11/2022 9:49:58 am Electric Kiwi | Juice Hackers ***@***.***>:
