### ISSUE TITLE
Account balance endpoint not returning balance

### ISSUE THREAD

**Issue by mikey0000** [electrickiwi-nz/api-samples#8]
Getting this error with the sample users, tried +1 and +2, Could I get some guidance here, my Home Assistant integration has one sensor (for a start) and pulls in the account balance. Would be good to show a demo to you as its working now once this issue is resolved.

{'error': {'code': 231, 'detail': 'Error getting account running balance data', 'title': 'Account running balance error'}, 'map_key_suffix': 'map', 'status': 1}

**Comment by mikey0000** [comment]
Also whats the process for go live? Getting pretty close now.

**Comment by electrickiwi-nz** [comment]
@mikey0000 - thanks for your note. 

1. I have a ticket out to the team on the error that you are receiving as there was a deployment on Friday which looks to have broken this endpoint. I will let you know when there is a fix in place. Sorry about that - looks like our testing didn't catch that one. 

2. For the Go Live process [send us](https://developer.electrickiwi.co.nz/support/) a link to your GitHub repository that contains your live widget source code so we can fork and review. Once we've confirmed there are no nasties will issue you with live access keys, which you can replace along with the live OAuth URL's and you should be able to use the live data specific to the user that logs in. 


Cheers, Matt

**Comment by mikey0000** [comment]
The go live link/button isn't working by the way.

Can I just link to it here, I'll provide instructions on how to get it working, using the dev container is probably the easiest way, also need thst endpoint working 😅

19/12/2022 9:43:17 am Electric Kiwi | Juice Hackers ***@***.***>:

> @mikey0000[https://github.com/mikey0000] - thanks for your note.
> 
1. > I have a ticket out to the team on the error that you are receiving as there was a deployment on Friday which looks to have broken this endpoint. I will let you know when there is a fix in place. Sorry about that - looks like our testing didn't catch that one.
> 
2. > For the Go Live process send us[https://developer.electrickiwi.co.nz/support/] a link to your GitHub repository that contains your live widget source code so we can fork and review. Once we've confirmed there are no nasties will issue you with live access keys, which you can replace along with the live OAuth URL's and you should be able to use the live data specific to the user that logs in.

**Comment by electrickiwi-nz** [comment]
@mikey0000 - strange that the link is not working for you. If you can send an email to [golive@electrickiwi.co.nz](golive@electrickiwi.co.nz) with the right details of your repo and appropriate README details on getting the app up and running. It will go to the right teams to review and provide the live access credentials. 

Cheers, Matt

**Comment by electrickiwi-nz** [comment]
@mikey0000 - sorry for the late response. The team has made some adjustments based on the last deploy to the sandbox and fixed the `/account/running_balance/{customer_number}/` endpoint and after testing with multiple users it is working as expected again. 

Sorry for the inconvenience. Cheers, Matt

**Comment by mikey0000** [comment]
Cheers Matt, I'll check my home assistant integration later today.
