### ISSUE TITLE
Unable to get Access Token - getting http 500 error

### ISSUE THREAD

**Issue by stephenpstanley** [electrickiwi-nz/api-samples#9]
I've tried using postman which has some nice tools to get access and refresh tokens to execute requests and even tried using CURL, but I'm unable even to get an access token

My CURL command is:

curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -d "grant_type=authorization_code&redirect_uri=<my_callback_uri>
&client_id=<my_Client_Id>&client_secret=<my_Client_secret>&username=api_dev+31@ekay.co.nz&password=Ekay123456\!" https://welcome-dev.electrickiwi.co.nz/oauth/authorize

The response I get back is:

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
 
Is it my request or is your server having problems?

**Comment by electrickiwi-nz** [comment]
@stephenpstanley - thanks for your note ... we utilise OAuth2 with the [Authentication Coed flow](https://auth0.com/docs/get-started/authentication-and-authorization-flow/authorization-code-flow) to give your application access to a specific logged in users data. 

The `curl` request you are making won't work if you look to the flow - if you are using `postman` I suggest you follow a [tutorial](https://www.toolsqa.com/postman/oauth-2-0-authorization-with-postman/) using the credentials and URLs we sent you. For the callback URI you can use `http://localhost:5080/callback` per the [sample code](https://github.com/electrickiwi-nz/api-samples). 

This should give you a `Bearer` token that you can use as the `Authorization` header as part of requests to any of the endpoints that your client_id has access to specific to the scopes. 

I hope this helps ... 

Cheers, Matt

**Comment by stephenpstanley** [comment]
Hi Matt

I can get the postman example accessing imgur without issues, but I just can't get an access token from Electric Kiwi

I've tried both using the callback URL I provided when I requested access and http://localhost:5080/callback as you suggested

Does this response give you any clues what I might be doing wrong?

GET https://welcome-dev.electrickiwi.co.nz/oauth/authorize?response_type=code&client_id=***********************&state=some-random-text-for-xss&scope=refresh_token&redirect_uri=http%3A%2F%2Flocalhost%3A5080%2Fcallback: {
  "Request Headers": {
    "upgrade-insecure-requests": "1",
    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Postman/10.6.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36",
    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
    "sec-fetch-site": "none",
    "sec-fetch-mode": "navigate",
    "sec-fetch-user": "?1",
    "sec-fetch-dest": "document",
    "accept-encoding": "gzip, deflate, br",
    "accept-language": "en-US"
  },
  "Response Headers": {
    "access-control-allow-headers": "DNT,X-apiversion,X-client,X-token,X-sid,Authorization,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range",
    "access-control-allow-methods": "GET, POST, OPTIONS",
    "access-control-allow-origin": "*",
    "access-control-expose-headers": "DNT,X-apiversion,X-client,X-token,X-sid,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range",
    "content-encoding": "gzip",
    "content-type": "text/html; charset=utf-8",
    "date": "Mon, 26 Dec 2022 23:02:22 GMT",
    "server": "nginx"
  }
}
POST https://welcome-dev.electrickiwi.co.nz/oauth/authorize?response_type=code&client_id=******************************&state=some-random-text-for-xss&scope=refresh_token&redirect_uri=http%3A%2F%2Flocalhost%3A5080%2Fcallback: {
  "Request Headers": {
    "upgrade-insecure-requests": "1",
    "origin": "https://welcome-dev.electrickiwi.co.nz",
    "content-type": "application/x-www-form-urlencoded",
    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Postman/10.6.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36",
    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
    "sec-fetch-site": "same-origin",
    "sec-fetch-mode": "navigate",
    "sec-fetch-user": "?1",
    "sec-fetch-dest": "document",
    "referer": "https://welcome-dev.electrickiwi.co.nz/oauth/authorize?response_type=code&client_id=*******************************&state=some-random-text-for-xss&scope=refresh_token&redirect_uri=http%3A%2F%2Flocalhost%3A5080%2Fcallback",
    "accept-encoding": "gzip, deflate, br",
    "accept-language": "en-US"
  },
  "Response Headers": {
    "access-control-allow-headers": "DNT,X-apiversion,X-client,X-token,X-sid,Authorization,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range",
    "access-control-allow-methods": "GET, POST, OPTIONS",
    "access-control-allow-origin": "*",
    "access-control-expose-headers": "DNT,X-apiversion,X-client,X-token,X-sid,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range",
    "content-length": "0",
    "content-type": "text/html; charset=utf-8",
    "date": "Mon, 26 Dec 2022 23:02:55 GMT",
    "location": "http://localhost:5080/callback?code=lVQCgdhE4hsWUGukqtCq0kz2iZZMbNf8ObqFqFt5sZtBgpys&state=some-random-text-for-xss",
    "server": "nginx"
  }
}
POST https://welcome.electrickiwi.co.nz/oauth/token: {
  "Error": "read ECONNRESET",
  "Request Headers": {
    "content-type": "application/x-www-form-urlencoded",
    "authorization": "Basic VEpkS1puRVZFSnVicUhQWGE3bXdsSm9ZOjB1aE1lWkl2R2xHTHhtbkdoYjRsMkFSZG0xSTZMUnlpS2gzQ1hTSEZTMVVtekZCbA==",
    "user-agent": "PostmanRuntime/7.30.0",
    "accept": "*/*",
    "cache-control": "no-cache",
    "postman-token": "d04cd567-194f-41d1-8d1b-2cbf24b7e726",
    "host": "welcome.electrickiwi.co.nz",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive"
  },
  "Request Body": {
    "grant_type": "authorization_code",
    "code": "lVQCgdhE4hsWUGukqtCq0kz2iZZMbNf8ObqFqFt5sZtBgpys",
    "redirect_uri": "http://localhost:5080/callback"
  }
}
Error: read ECONNRESET

**Comment by electrickiwi-nz** [comment]
@stephenpstanley - thanks for posting the flow you are trying ... the error you are seeing is because you need to initially get a code by logging into our authorization server using the following URL in a browser - it is interactive and you need to login using our test users: 

```
u: api_dev+[1->50]@ekay.co.nz
p: Ekay123456!
```

```
https://welcome-dev.electrickiwi.co.nz/oauth/authorize?response_type=code&client_id=************************&scope=read_customer_detail%20read_consumption_summary%20read_consumption_averages%20read_hop_intervals_config%20read_hop_connection%20save_hop_connection%20read_session&redirect_uri=http%3A%2F%2Flocalhost%3A5080%2Fcallback
```

This will take you to the `&redirect_uri=http%3A%2F%2Flocalhost%3A5080%2Fcallback` page which will have a code included in the URI e.g. `http://localhost:5080/callback?code=DpKdn0r6Iysxizbi4WuqLrZ36bDK7jtraOZY61Y9lOQ1SHWi`

But because you are not running a server on localhost:5080/callback the page will through an error. 

With the code you can use cURL to get a `Bearer` token to use with API endpoint requests. e.g. 

```
curl \
--request POST \
--data "code=DpKdn0r6Iysxizbi4WuqLrZ36bDK7jtraOZY61Y9lOQ1SHWi&client_id=****************&client_secret=*******************&redirect_uri=http://localhost:5080/callback&grant_type=authorization_code" \
https://welcome-dev.electrickiwi.co.nz/oauth/token
```

This will give you are response of:

```
{"access_token": "LPhI9pM1nreTBoHVNX2Lzq5ryCdsTzPgSmlB6JRMj1", "client_id": "*********************", "customer_number": 1000004, "expires_in": 1200, "issued_at": 1672188896.0110176, "refresh_token": "W735x8MVsn3eEug7KjmS7SzCnwvvvlYD8PSPewldrkNSOOgg", "revoked": false, "scope": "read_customer_detail read_consumption_summary read_consumption_averages read_hop_intervals_config read_hop_connection save_hop_connection read_session", "session_key": "YsLFbRDR0zltqoOcOnPnZEZ43o0N1T5S", "token_type": "Bearer"}
```

The `access_token` can now be used within API Endpoint requests 

```
curl --request GET \
  --url https://api-dev.electrickiwi.co.nz/session/ \
  --header 'Authorization: Bearer LPhI9pM1nreTBoHVNX2Lzq5ryCdsTzPgSmlB6JRMj1'
```

I think the issue here is that `Authorization Code` OAuth2 flow requires a valid customer login - with requires a interactive browser session to login. 

If you run any of our [API Samples](https://github.com/electrickiwi-nz/api-samples) you will find they all require a login to get a Bearer token and start interacting with our API endpoints to access data. 

I hope this helps. Cheers, Matt

**Comment by electrickiwi-nz** [comment]
@stephenpstanley - I have also tested this using POSTMAN to confirm that it is working correctly and it is... please follow the same [tutorial](https://www.toolsqa.com/postman/oauth-2-0-authorization-with-postman/) replacing the correct Auth URL, Access Token URL, Scope, Callback URL, Client ID and Client Secret with the ones we sent you. 

You should be able to generate an Access token that you can use. 

<img width="1066" alt="Screenshot 2022-12-28 at 2 08 29 PM" src="https://user-images.githubusercontent.com/69653109/209742272-14d5b180-f6e0-49de-81bf-dba3e91f4bfe.png">

**Comment by stephenpstanley** [comment]
Thanks Matt.  Making slow progress.  I've managed to follow the steps and got an authorization code, but I'm clearly falling over when trying to do the following requests from postman

https://api-dev.electrickiwi.co.nz/session/
https://api-dev.electrickiwi.co.nz/customer/1000001/

They both return an invalid URL error

{
    "error": {
        "code": 404,
        "detail": "Please check URI , query params and request body and try again",
        "title": "Invalid API Call. Endpoint not found"
    },
    "status": 1
}

I appreciate your help, clearly I'm stumbling along!

**Comment by mikey0000** [comment]
@stephenpstanley checkout my electric kiwi python API, not sure what language your using but I've gotten over the majority of hurdles with accessing the API and getting refresh tokens as well.

**Comment by electrickiwi-nz** [comment]
@stephenpstanley - sorry for the late response and picking up from where you left off ... I think you are making great progress. 

I have tested the access to those two URLs and successfully get a response. 

The API works in such a way that your authentication determines the access to what resources based on the scopes you pass as you are authenticating. For your client_id you have these scopes:
- read_customer_detail
- read_consumption_summary
- read_consumption_averages
- read_hop_intervals_config
- read_hop_connection
- save_hop_connection
- read_session

and you should be adding them to POSTMAN when generating your bearer token:
![image](https://user-images.githubusercontent.com/69653109/215029774-99694df6-b174-4d8b-a00a-9cfdab783cd3.png)

Without these being passed you will receive a 404 or 401 response. 

Also for the /customer/1000001/ endpoint - you need to make sure you have logged in with the correct customer which you will get from the /session/ endpoint. e.g. session response will provide a `customer_number` key which you use in the /customer/`customer_number`/ endpoint.
```
{
    "data": {
        "customer": [
            {
                "customer_number": 1000005,
```

I hope this helps... continue to let me know how you are getting on.
